def create_llm_input(study_id, validated_findings, clinical_context):
    """
    Prepare the data that is allowed to reach the LLM.

    Only findings explicitly approved by the radiologist
    are allowed into the LLM input.
    """

    approved_findings = [
        finding
        for finding in validated_findings
        if finding["status"] == "APPROVED"
    ]

    return {
        "study_id": study_id,
        "approved_findings": approved_findings,
        "clinical_context": clinical_context
    }


def create_llm_output(draft_report, patient_explanation):
    """
    Return the two outputs generated by Member 2.
    """

    return {
        "draft_report": draft_report,
        "patient_explanation": patient_explanation
    }